# -*- coding: utf-8 -*-
"""lab_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13HC3icbEZwcXXqzBedJzxRAcKRmbokhC
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

text = """
artificial intelligence is transforming modern society.
it is used in healthcare finance education and transportation.
machine learning allows systems to improve automatically with experience.
data plays a critical role in training intelligent systems.
large datasets help models learn complex patterns.
deep learning uses multi layer neural networks.
neural networks are inspired by biological neurons.
each neuron processes input and produces an output.
training a neural network requires optimization techniques.
gradient descent minimizes the loss function.
"""

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

total_words = len(tokenizer.word_index) + 1

input_sequences = []

for line in text.split("\n"):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        input_sequences.append(token_list[:i+1])

max_len = max(len(seq) for seq in input_sequences)
input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')

X = input_sequences[:, :-1]
y = input_sequences[:, -1]

model = Sequential([
    Embedding(total_words, 50, input_length=max_len-1),
    LSTM(100),
    Dense(total_words, activation='softmax')
])

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.summary()

model.fit(X, y, epochs=200, verbose=1)

def generate_text(seed_text, next_words):
    for _ in range(next_words):
        seq = tokenizer.texts_to_sequences([seed_text])[0]
        seq = pad_sequences([seq], maxlen=max_len-1, padding='pre')
        predicted = np.argmax(model.predict(seq, verbose=0))

        for word, index in tokenizer.word_index.items():
            if index == predicted:
                seed_text += " " + word
                break
    return seed_text

print(generate_text("artificial intelligence", 10))

from tensorflow.keras.layers import Input, Dense, LayerNormalization, MultiHeadAttention
from tensorflow.keras.models import Model

X = input_sequences[:, :-1]
y = input_sequences[:, -1]

X = X.astype(np.int32)
y = y.astype(np.int32)

def positional_encoding(seq_len, d_model):
    pos = np.arange(seq_len)[:, np.newaxis]
    i = np.arange(d_model)[np.newaxis, :]
    angle_rates = 1 / np.power(10000, (2 * (i//2)) / np.float32(d_model))
    angle_rads = pos * angle_rates
    angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
    angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])
    return tf.cast(angle_rads, dtype=tf.float32)

def transformer_block(x, head_size, num_heads, ff_dim):
    attn = MultiHeadAttention(num_heads=num_heads, key_dim=head_size)(x, x)
    x = LayerNormalization()(x + attn)
    ff = Dense(ff_dim, activation='relu')(x)
    ff = Dense(head_size)(ff)
    return LayerNormalization()(x + ff)

inputs = Input(shape=(max_len-1,))
embedding = Embedding(total_words, 64)(inputs)
pos_embed = positional_encoding(max_len-1, 64)
x = embedding + pos_embed

x = transformer_block(x, 64, 2, 128)
x = Dense(64, activation='relu')(x)
outputs = Dense(total_words, activation='softmax')(x[:, -1])

transformer_model = Model(inputs, outputs)

transformer_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

transformer_model.summary()

transformer_model.fit(X, y, epochs=100, verbose=1)

def generate_transformer_text(seed_text, next_words):
    for _ in range(next_words):
        seq = tokenizer.texts_to_sequences([seed_text])[0]
        seq = pad_sequences([seq], maxlen=max_len-1, padding='pre')
        pred = np.argmax(transformer_model.predict(seq, verbose=0))

        for word, index in tokenizer.word_index.items():
            if index == pred:
                seed_text += " " + word
                break
    return seed_text

print(generate_transformer_text("machine learning", 10))